# Generated by Django 4.2.4 on 2023-09-22 00:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='لوازم همراه')),
            ],
            options={
                'verbose_name': 'لوازم همراه',
                'verbose_name_plural': 'لوازم همراه',
            },
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance_problem', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='برند')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='قطعه')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveBigIntegerField(unique=True, verbose_name='شماره تلفن')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری ها',
            },
        ),
        migrations.CreateModel(
            name='CustomerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_password', models.CharField(blank=True, max_length=20, null=True, verbose_name='پسورد دستگاه')),
                ('device_serial_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='سریال دستگاه')),
                ('import_files', models.BooleanField(blank=True, null=True, verbose_name='اطلاعات مهم')),
                ('import_files_detail', models.TextField(blank=True, null=True, verbose_name='جزئیات اطلاعات مهم')),
                ('accessories', models.BooleanField(blank=True, null=True, verbose_name='لوازم همراه')),
                ('problem_detail', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('appearance_detail', models.TextField(blank=True, null=True, verbose_name='جزئیات ظاهر')),
                ('accessories_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.accessories', verbose_name='لوازم همراه')),
                ('appearance', models.ForeignKey(blank=True, default='سالم', null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.appearance', verbose_name='ظاهر')),
            ],
            options={
                'verbose_name': 'دستگاه',
                'verbose_name_plural': 'دستگاه های مشتری',
            },
        ),
        migrations.CreateModel(
            name='DeviceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نوع دستگاه')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='عنوان مشکل')),
            ],
        ),
        migrations.CreateModel(
            name='Serviceman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام سرویس دهنده')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('reception_datetime', django_jalali.db.models.jDateField(default=datetime.date(2023, 9, 22), editable=False, verbose_name='تاریخ پذیرش')),
                ('reception_datetime_m', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی')),
                ('reception_no', models.BigAutoField(primary_key=True, serialize=False, unique_for_date=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ میلادی'), verbose_name='شماره پذیرش')),
                ('reception_type', models.CharField(choices=[('1', 'حضوری'), ('2', 'آنلاین')], default='1', max_length=2, verbose_name='نوع پذیرش')),
                ('service_type', models.CharField(choices=[('1', 'تعمیر'), ('2', 'گارانتی')], default='1', max_length=2, verbose_name='نوع خدمات')),
                ('deposit', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='بیعانه')),
                ('estimated_cost', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='هزینه حدودی')),
                ('preparation', django_jalali.db.models.jDateField(blank=True, default=datetime.date(2023, 9, 25), null=True, verbose_name='زمان تحویل حدودی')),
                ('status', models.CharField(choices=[('1', 'پذیرش شده'), ('2', 'در حال تعمیر'), ('3', 'آماده تحویل'), ('4', 'تحویل داده شده')], default='1', max_length=2, verbose_name='وضعیت')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.customer', verbose_name='مشتری')),
                ('customer_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_task', to='reception.customerdevice', verbose_name='دستگاه')),
                ('serviceman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.serviceman', verbose_name='کاربر پذیرش')),
            ],
            options={
                'verbose_name': 'پذیرش',
                'verbose_name_plural': 'لیست پذیرش',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_detail', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('device', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='دستگاه')),
                ('status', models.CharField(choices=[('1', 'پذیرش شده'), ('2', 'در دست انجام'), ('3', 'انجام شده')], default='1', max_length=2, verbose_name='وضعیت')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.component', verbose_name='قطعه')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_name', to='reception.problemtype', verbose_name='مشکل')),
                ('serviceman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.serviceman', verbose_name='سرویس دهنده')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_problem', to='reception.task', verbose_name='مشکل')),
            ],
            options={
                'verbose_name': 'مشکل',
                'verbose_name_plural': 'مشکلات',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_photo', to='reception.task')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس های دستگاه',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='مدل')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.brand', verbose_name='برند')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.devicetypes', verbose_name='نوع دستگاه')),
            ],
            options={
                'verbose_name': 'دستگاه',
                'verbose_name_plural': 'دستگاه ها',
            },
        ),
        migrations.AddField(
            model_name='customerdevice',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.device', verbose_name='دستگاه'),
        ),
        migrations.AddField(
            model_name='customerdevice',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_photo', to='reception.photo'),
        ),
        migrations.AddField(
            model_name='customerdevice',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.problem', verbose_name='مشکل دستگاه'),
        ),
        migrations.AddField(
            model_name='customerdevice',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_device_task', to='reception.task'),
        ),
    ]
